name: Qualité de Code

on: [push]
  
    

jobs:
  pipeline:
    runs-on: macos-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4  
      - name: Installer Composer
        run:
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Installer PHP_CodeSniffer
        run: 
          composer require --dev squizlabs/php_codesniffer

      - name: Linter PHP_CodeSniffer (PHP Standards)
        run: 
          vendor/bin/phpcs --standard=PSR12 C:\Users\lenovo\td5  # Remplace "src" par ton répertoire de code
