name: Qualité de Code

on: [push]
  
    

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      
      - name: Installer PHP
        run: 
          sudo apt update
          sudo apt install -y php php-cli php-xml php-mbstring  # Installer PHP et ses extensions nécessaires

      - name: Installer Composer
        run: 
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Installer PHP_CodeSniffer
        run: 
          composer require --dev squizlabs/php_codesniffer

      - name: Linter PHP_CodeSniffer (PHP Standards)
        run: 
          vendor/bin/phpcs --standard=PSR12 C:\Users\lenovo\td5  # Remplace "src" par ton répertoire de code
